import "./globals.css";
import { Inter } from "next/font/google";

import Navbar from "@/components/section/NavBar";
import Footer from "@/components/section/Footer";

const inter = Inter({ subsets: ["latin"] });
import SearchProvider from "../context/searchContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} max-w-none w-auto `}>
        <SearchProvider>
          <Navbar />
          {children}
          <Footer />
        </SearchProvider>
      </body>
    </html>
  );
}
